# build environment
FROM node:alpine as builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --silent
COPY . /usr/src/app
RUN npm run build

# production environment
FROM nginx:alpine
COPY --from=builder /usr/src/app/build /usr/src/app/build
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]