version: '2.1'

services:
  seed-frontend:
    container_name: seed-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    image: seed-frontend-prod
    ports:
      - 8080:80
    depends_on:
      - seed-backend

  seed-backend:
    container_name: seed-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    image: seed-backend-prod
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: demo-prod
      DB_HOST: database
      DB_PORT: 3306
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: seed-db-prod
    image: mysql:5.7
    volumes:
      - ./data/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo-prod
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
